title = "Custom Gitleaks Config for CI/CD Demo"
description = "Secret scanning ruleset for interview project"
report = "json"

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|token)\s*=\s*['|"][0-9a-zA-Z-_]{16,45}['|"]'''
tags = ["apikey", "security"]

[[rules]]
id = "password-detection"
description = "Hardcoded password"
regex = '''(?i)(password|passwd|pwd)\s*=\s*['|"].+['|"]'''
tags = ["password", "security"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "security"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN( RSA)? PRIVATE KEY-----'''
tags = ["key", "security"]

